name: GenerateSnake
on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"

jobs:
  update-repository:
    name: Update this repo's README with repository_owner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Generate Snake
        uses: Platane/snk/svg-only@v3.2.0
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            ./img/github-contribution-grid-snake.svg
            ./img/github-contribution-grid-snake-dark.svg?palette=github-dark
      - name: Push to GitHub
        uses: EndBug/add-and-commit@v9.1.4
        with:
          message: ":rocket: Update"
